# Generated by Django 3.0.3 on 2020-05-11 16:07

from django.db import migrations, models
import dsl_dashboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('dsl_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittercampaign',
            name='upload',
            field=models.FileField(default='logo.png', upload_to=dsl_dashboard.models.user_directory_path),
            preserve_default=False,
        ),
    ]
