# Generated by Django 3.0.3 on 2020-03-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('consumer_key', models.CharField(max_length=200)),
                ('consumer_secret_key', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('access_token_secret', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('twitter_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_account', to='dsl_dashboard.TwitterAccount')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=240)),
                ('scheduled_time', models.DateTimeField()),
                ('campaign_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_name', to='dsl_dashboard.TwitterCampaign')),
            ],
        ),
    ]
