# Generated by Django 3.0.3 on 2020-06-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200531_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledPost',
        ),
    ]
